main:
  - name: Search
    url: '/search/'
    weight: 5
  - name: Archive
    url: '/archive/'
    weight: 10
  - name: Categories
    url: '/categories'
    weight: 15
  - name: Resume
    url: '/resume'
    weight: 20
