homeInfoParams:
    Title: "Plugged Into Matrix"
    Content: Hey, it's [Fahim Montasir Misbah](/about). This blog is actually a dumpster. I write about a lot of stuffs, and I'll dump some of them here when I feel like it. So more likely this place will become a mess over time. And there's also a [Bangla](/bn/) section that you can look over. Make yourself at home, have a good day! :)
    # ![Fahim Montasir](/img/avatar-circle.webp)