baseURL: "https://fahimscirex.github.io/"
title: Fahim Montasir Misbah
paginate: 5
theme: papermod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Search
                  url: search
                  weight: 5
                - name: Categories
                  url: categories
                  weight: 10
                - name: Contact
                  url: contact
                  weight: 10
             #   - name: Categories
             #     url: categories/
             #     weight: 10

    bn:
        languageName: ":bn:"
        languageAltTitle: Bangla
        weight: 2
        title: Fahim Montasir Misbah
        profileMode:
            enabled: false
        menu:
            main:
                - name: খোঁজ - দ্য সার্চ
                  url: https://fahimscirex.github.io/search
                  weight: 5
                - name: বিভাগ
                  url: https://fahimscirex.github.io/bn/categories
                  weight: 10
                - name: যোগাযোগ
                  url: https://fahimscirex.github.io/contact
                  weight: 10
        #        - name: xxxx
        #          url: xxxx
        #          weight: 10
        homeInfoParams:
                Title: "ফাহিম মোন্তাসির মিসবাহ"
                Content: >
                        ![Fahim Montasir](/img/avatar-circle.webp)


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Fahim Montasir Misbah
    description: "A FOSS enthusiast from Dhaka, Bangladesh. Covering Linux, Books, Movies, Music and random stuffs in this blog."
    keywords: [Blog, fahimscirex, FOSS]
    author: Fahim Montasir Misbah
    # author: ["Me", "You"] # multiple authors
    images: ["/img/blog-banner.webp"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: true
    disableScrollToTop: false
    comments: true
    hidemeta: true
    hideSummary: false
    showtoc: false
    tocopen: false

    homeInfoParams:
        Title: "Fahim Montasir Misbah"
        Content: >
             ![Fahim Montasir](/img/avatar-circle.webp)

    socialIcons:
        - name: telegram
          url: "https://t.me/fahimscirex"    
        - name: twitter
          url: "https://twitter.com/"
        - name: mastodon
          url: "https://fosstodon.org/web/accounts/313800"
        - name: github
          url: "https://github.com/fahimscirex"
        - name: goodreads
          url: "https://goodreads.com/fahimscirex"
        - name: twitter
          url: "https://twitter.com/fahimscirex"

    editPost:
        URL: "https://github.com/fahimscirex/fahimscirex.github.io/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    analytics:
        google:
            SiteVerificationTag: "yBRESuR4j8lYoZ7IGugAaYEZ0c6dU0uj8n7Y-wrXPdg"

    label:
         text: "/"
         icon: /img/avatar-circle.webp
         iconHeight: 35

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "img/favicon.ico"
        favicon16x16: "img/favicon.ico"
        #favicon32x32: "<link / abs url>"
        apple_touch_icon: "img/favicon.ico"
        #safari_pinned_tab: "<link / abs url>"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
